using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

/**********************************************************************************************************
 * Creator: Thelma Nora
 * CIST 2381(Mobile Application Development
 * This game was created by me, i did not copy an existing code online and claim it as my own.
 * This is a guessing game that allows the player to generate a random number when they start the game
 * The player then has to guess what number was generated by the game.When the player has successfully 
 * guessed the correct number the game will indicate how many tries the player had before they guessed 
 * the correct number. The player also gets notifed if the number they guessed is high or lower than 
 * the correct number until they have guess the correct number.
 * *******************************************************************************************************/

namespace GuessingGame
{
    public partial class MainPage : ContentPage
    {
        int randomNumber;
        int guessedNumber;
        int numberOfGuesses;
        bool isRandomButtonClickedBeforeGuessing = false;

        public MainPage()
        {
            InitializeComponent();
        }

        private void RandomButton_Clicked(object sender, EventArgs e)
        {
            Random rn = new Random();
            randomNumber = rn.Next(1, 101);
            instruct.Text = "Enter a number below and click on Guess to see if you guessed correctly";
            isRandomButtonClickedBeforeGuessing = true;
        }

        private async void GuessButton_Clicked(object sender, EventArgs e)
        {
            bool isTextANumber = int.TryParse(UserInputEntry.Text.Trim(), out guessedNumber);

            if (isTextANumber)
            {
                if (isRandomButtonClickedBeforeGuessing)
                {
                    if (guessedNumber < randomNumber)
                    {
                        ResultLabel.Text = "You have guessed a number that is less than the games number, you may try again!";
                    }
                    else if (guessedNumber > randomNumber)
                    {
                        ResultLabel.Text = "You have guessed a number that is higher than the games number, you may try again!";
                    }
                    else
                    {
                        ResultLabel.Text = "Correct!!! the number generated by the game was: " + randomNumber.ToString();
                        CountLabel.Text = $"The number of tries it took you to guess the correct number is {numberOfGuesses}";
                    }

                    numberOfGuesses++;
                }
                else
                {
                    await DisplayAlert("Warning", "Click on Start Game to generate random number", "Ok");
                }
            }
            else
            {
                await DisplayAlert("Warning", $"'{UserInputEntry.Text}' is not a valid numeric number", "Ok");
            }
        }

        private async void PlayAgainButton_Clicked(object sender, EventArgs e)
        {
            bool didUserClickOk = await DisplayAlert("Good Job!", "Click on Start Game to begin a new game", "Ok", "Cancel");

            if (didUserClickOk)
            {
                guessedNumber = 0;
                UserInputEntry.Text = string.Empty;
                ResultLabel.Text = string.Empty;
                CountLabel.Text = string.Empty;
                instruct.Text = string.Empty;
                numberOfGuesses = 0;
                isRandomButtonClickedBeforeGuessing = false;
            }
        }
    }
}
