using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

/**********************************************************************************************************
 * Creator: Thelma Nora
 * CIST 2381(Mobile Application Development
 * This game was created by me, i did not copy an existing code online and claim it as my own.
 * This is a guessing game that allows the player to generate a random number when they start the game
 * The player then has to guess what number was generated by the game.When the player has successfully 
 * guessed the correct number the game will indicate how many tries the player had before they guessed 
 * the correct number. The player also gets notifed if the number they guessed is high or lower than 
 * the correct number until they have guess the correct number.
 * *******************************************************************************************************/

namespace GuessingGame
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }
        int n;
        int g;
        int tries;
        private void rand_Clicked(object sender, EventArgs e)
        {
            Random rn = new Random();
            n = rn.Next(1, 101);
            instruct.Text = "Enter a number below and click on Guess to see if you guessed correctly";
            randClicked = true;
        }
        private bool randClicked = false;
        private void guess_Clicked(object sender, EventArgs e)
        {
            if (randClicked == true)
            {
                g = int.Parse(gnum.Text);
                if (g < n)
                {
                    result.Text = "You have guessed a number that is less than the games number, you may try again!";
                }
                else if (g > n)
                {
                    result.Text = "You have guessed a number that is higher than the games number, you may try again!";
                }
                else
                {
                    result.Text = "Correct!!! the number generated by the game was: " + n.ToString();
                    count.Text = $"The number of tries it took you to guess the correct number is {tries}";
                }
                tries++;
            }
            else
            {
                DisplayAlert("Warning", "Click on Start Game to generate random number", "Ok");
            }

        }
        public void again_Clicked(object sender, EventArgs e)
        {
            DisplayAlert("Good Job!", "Click on Start Game to begin a new game", "Ok");
            if (true)
            {

                g = 0;
                gnum.Text = null;   
                result.Text = null;
                count.Text = null;
                instruct.Text = null;
                tries = 0;
                randClicked = false;
            }
        }

    }


}
